### ISSUE TITLE
scheduler not found

### ISSUE THREAD

**Issue by meilihao** [pingcap/tidb-ansible#1052]
rolling update from 5.7.25-TiDB-v4.0.0-alpha-531-g46c3f1a91 to latest,today:
```
$ ansible-playbook local_prepare.yml -c local
...
ERROR MESSAGE SUMMARY **********************************************************************************************************************************************
[172.19.136.22]: Ansible FAILED! => playbook: rolling_update.yml; TASK: remove evict-leader-scheduler; message: {"access_control_allow_headers": "accept, content-type, authorization", "access_control_allow_methods": "POST, GET, OPTIONS, PUT, DELETE", "access_control_allow_origin": "*", "changed": false, "connection": "close", "content": "\"scheduler not found\"\n", "content_length": "22", "content_type": "application/json; charset=UTF-8", "date": "Fri, 06 Dec 2019 06:21:46 GMT", "json": "scheduler not found", "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://172.19.136.22:12379/pd/api/v1/schedulers/evict-leader-scheduler-1"}
```

**Comment by liubo0127** [comment]
It looks like the `pd` service was abnormal at the time. Please confirm that all services in the cluster are normal, then execute again.

**Comment by meilihao** [comment]
service is ok: i can create table. i got the same error on the next try.

**Comment by liubo0127** [comment]
Just looking at the database can't determine the cluster status, because we are distributed, and some nodes have problems that will not affect the service. You can use the `overview` dashboard on `grafana` to see if each node is running normally. Monitoring instructions refer to `https://pingcap.com/docs-cn/stable/reference/key-monitoring-metrics/overview-dashboard/`

Please send me how many `pd` and `tikv` nodes in this cluster, and has anyone changed the scheduler during `rolling update`?

**Comment by meilihao** [comment]
my env:
1 pd
1 tidb
1 tikv

Only i am using cluster.

overview:
![深度截图_选择区域_20191209214031](https://user-images.githubusercontent.com/4382586/70440223-a9a47780-1acc-11ea-815f-4f27b5a8bab2.png)


I stopped the cluster, then restart, got some error: 
tidb.log:
```
[2019/12/09 22:30:11.928 +08:00] [WARN] [main.go:170] ["config file conf/tidb.toml contained unknown configuration options: log.file.log-rotate"]
[2019/12/09 22:30:11.928 +08:00] [INFO] [printer.go:40] ["Welcome to TiDB."] ["Release Version"=v4.0.0-alpha-531-g46c3f1a91] ["Git Commit Hash"=46c3f1a91662788a4d59a33f0683232ef5a57c32] ["Git Branch"=master] ["UTC Build Time"="2019-10-16 12:58:44"] [GoVersion="go version go1.13 linux/amd64"] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2019/12/09 22:30:11.929 +08:00] [INFO] [printer.go:53] ["loaded config"] [config="{\"host\":\"0.0.0.0\",\"advertise-address\":\"172.19.136.22\",\"port\":4000,\"cors\":\"\",\"store\":\"tikv\",\"path\":\"172.19.136.22:12379\",\"socket\":\"\",\"lease\":\"45s\",\"run-ddl\":true,\"split-table\":true,\"token-limit\":1000,\"oom-use-tmp-storage\":true,\"oom-action\":\"log\",\"mem-quota-query\":34359738368,\"enable-streaming\":false,\"txn-local-latches\":{\"enabled\":true,\"capacity\":2048000},\"lower-case-table-names\":2,\"log\":{\"level\":\"info\",\"format\":\"text\",\"disable-timestamp\":false,\"disable-error-stack\":true,\"file\":{\"filename\":\"/home/tidb/deploy/log/tidb.log\",\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"slow-query-file\":\"/home/tidb/deploy/log/tidb_slow_query.log\",\"slow-threshold\":300,\"expensive-threshold\":10000,\"query-log-max-len\":2048},\"security\":{\"skip-grant-table\":false,\"ssl-ca\":\"\",\"ssl-cert\":\"\",\"ssl-key\":\"\",\"cluster-ssl-ca\":\"\",\"cluster-ssl-cert\":\"\",\"cluster-ssl-key\":\"\"},\"status\":{\"status-host\":\"0.0.0.0\",\"metrics-addr\":\"\",\"status-port\":10080,\"metrics-interval\":15,\"report-status\":true,\"record-db-qps\":false},\"performance\":{\"max-procs\":0,\"max-memory\":0,\"stats-lease\":\"3s\",\"stmt-count-limit\":5000,\"feedback-probability\":0.05,\"query-feedback-limit\":1024,\"pseudo-estimate-ratio\":0.8,\"force-priority\":\"NO_PRIORITY\",\"bind-info-lease\":\"3s\",\"txn-total-size-limit\":104857600,\"tcp-keep-alive\":true,\"cross-join\":true,\"run-auto-analyze\":true},\"prepared-plan-cache\":{\"enabled\":false,\"capacity\":100,\"memory-guard-ratio\":0.1},\"opentracing\":{\"enable\":false,\"rpc-metrics\":false,\"sampler\":{\"type\":\"const\",\"param\":1,\"sampling-server-url\":\"\",\"max-operations\":0,\"sampling-refresh-interval\":0},\"reporter\":{\"queue-size\":0,\"buffer-flush-interval\":0,\"log-spans\":false,\"local-agent-host-port\":\"\"}},\"proxy-protocol\":{\"networks\":\"\",\"header-timeout\":5},\"tikv-client\":{\"grpc-connection-count\":16,\"grpc-keepalive-time\":10,\"grpc-keepalive-timeout\":3,\"commit-timeout\":\"41s\",\"max-batch-size\":128,\"overload-threshold\":200,\"max-batch-wait-time\":0,\"batch-wait-size\":8,\"enable-arrow\":true,\"region-cache-ttl\":600},\"binlog\":{\"enable\":false,\"ignore-error\":false,\"write-timeout\":\"15s\",\"binlog-socket\":\"\",\"strategy\":\"range\"},\"compatible-kill-query\":false,\"plugin\":{\"dir\":\"\",\"load\":\"\"},\"pessimistic-txn\":{\"enable\":true,\"max-retry-count\":256,\"ttl\":\"40s\"},\"check-mb4-value-in-utf8\":true,\"treat-old-version-utf8-as-utf8mb4\":true,\"enable-table-lock\":false,\"delay-clean-table-lock\":0,\"split-region-max-num\":1000,\"stmt-summary\":{\"max-stmt-count\":100,\"max-sql-length\":4096}}"]
[2019/12/09 22:30:11.929 +08:00] [INFO] [main.go:283] ["disable Prometheus push client"]
[2019/12/09 22:30:11.929 +08:00] [INFO] [store.go:68] ["new store"] [path=tikv://172.19.136.22:12379]
[2019/12/09 22:30:11.929 +08:00] [INFO] [client.go:144] ["[pd] create pd client with endpoints"] [pd-address="[172.19.136.22:12379]"]
[2019/12/09 22:30:11.929 +08:00] [INFO] [systime_mon.go:25] ["start system time monitor"]
[2019/12/09 22:30:11.931 +08:00] [INFO] [client.go:252] ["[pd] switch leader"] [new-leader=http://172.19.136.22:12379] [old-leader=]
[2019/12/09 22:30:11.932 +08:00] [INFO] [client.go:163] ["[pd] init cluster id"] [cluster-id=6716797090956080087]
[2019/12/09 22:30:11.947 +08:00] [INFO] [store.go:74] ["new store with retry success"]
[2019/12/09 22:30:11.966 +08:00] [INFO] [tidb.go:70] ["new domain"] [store=tikv-6716797090956080087] ["ddl lease"=45s] ["stats lease"=3s]
[2019/12/09 22:30:11.970 +08:00] [INFO] [ddl.go:427] ["[ddl] start DDL"] [ID=61cdd4bf-c2a4-407a-ae49-3fc4fd74da41] [runWorker=true]
[2019/12/09 22:30:11.973 +08:00] [INFO] [ddl.go:415] ["[ddl] start delRangeManager OK"] ["is a emulator"=false]
[2019/12/09 22:30:11.974 +08:00] [INFO] [ddl_worker.go:119] ["[ddl] start DDL worker"] [worker="worker 1, tp general"]
[2019/12/09 22:30:11.974 +08:00] [INFO] [ddl_worker.go:119] ["[ddl] start DDL worker"] [worker="worker 2, tp add index"]
[2019/12/09 22:30:12.055 +08:00] [INFO] [domain.go:142] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=540] ["start time"=67.241086ms]
[2019/12/09 22:30:12.056 +08:00] [INFO] [domain.go:351] ["full load and reset schema validator"]
2019/12/09 22:30:12.063 terror.go:342: [fatal] invalid marker byte, group bytes "\x00\x00\x00\x00\x00\x00\x00\x01\x00"
github.com/pingcap/tidb/util/codec.decodeBytes
	github.com/pingcap/tidb@/util/codec/bytes.go:93
github.com/pingcap/tidb/util/codec.DecodeBytes
	github.com/pingcap/tidb@/util/codec/bytes.go:124
github.com/pingcap/tidb/util/codec.(*Decoder).DecodeOne
	github.com/pingcap/tidb@/util/codec/codec.go:933
github.com/pingcap/tidb/distsql.(*selectResult).readRowsData
	github.com/pingcap/tidb@/distsql/select_result.go:261
github.com/pingcap/tidb/distsql.(*selectResult).readFromDefault
	github.com/pingcap/tidb@/distsql/select_result.go:174
github.com/pingcap/tidb/distsql.(*selectResult).Next
	github.com/pingcap/tidb@/distsql/select_result.go:159
github.com/pingcap/tidb/executor.(*indexWorker).extractTaskHandles
	github.com/pingcap/tidb@/executor/distsql.go:705
github.com/pingcap/tidb/executor.(*indexWorker).fetchHandles
	github.com/pingcap/tidb@/executor/distsql.go:662
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker.func1
	github.com/pingcap/tidb@/executor/distsql.go:480
runtime.goexit
	runtime/asm_amd64.s:1357
```

**Comment by liubo0127** [comment]
I have tested the locally, there is some problem in  `pd-server`, we will fix it.

If `tidb-server` keep reporting errors after restarting, you can create an issue in [TiDB Project](https://github.com/pingcap/tidb/issues).

**Comment by meilihao** [comment]
reported tidb error to pingcap/tidb#13086.

**Comment by liubo0127** [comment]
fix `scheduler not found` in https://github.com/pingcap/pd/pull/2031

**Comment by meilihao** [comment]
because the latest version no change for more 5 days, i switched tidb 4.0 -> 3.07, so can't test.

**Comment by liubo0127** [comment]
OK, I will sync information after the pr is committed.

**Comment by meilihao** [comment]
I don't know how to operate, the version changed back to 4.0, so i want to test the error, but get another error.

log:
```
$ cat inventory.ini
...
tidb_version = latest
....
$ ansible-playbook local_prepare.yml -c local
$ ansible-playbook rolling_update.yml -c local
....
TASK [get store info from PD] *************************************************************************************************************************************************************************************************************************************************
fatal: [172.19.136.22]: FAILED! => {"access_control_allow_headers": "accept, content-type, authorization", "access_control_allow_methods": "POST, GET, OPTIONS, PUT, DELETE", "access_control_allow_origin": "*", "changed": false, "connection": "close", "content": "PANIC: invalid schedule strategy: \"count\"\ngoroutine 313 [running]:\ngithub.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7fa678fa6770, 0xc0000aca70, 0xc0001a9540, 0xc0006b6800)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:159 +0xcb\npanic(0x11dbd60, 0xc00088bdc0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/pd/server/core.StringToScheduleStrategy(...)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/core/kind.go:90\ngithub.com/pingcap/pd/server/api.newStoreInfo(0xc0002b6780, 0xc0002630a0, 0xc0002630a0)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/api/store.go:86 +0x7fb\ngithub.com/pingcap/pd/server/api.(*storesHandler).ServeHTTP(0xc0002bdc90, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6f00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/api/store.go:423 +0x215\ngithub.com/pingcap/pd/server/api.clusterMiddleware.Middleware.func1(0x7fa678fa6770, 0xc0000aca78, 0xc0006b6e00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/api/middleware.go:44 +0x19b\nnet/http.HandlerFunc.ServeHTTP(0xc0006c4db0, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0002aa770, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6e00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/gorilla/mux@v1.6.1/mux.go:159 +0x104\ngithub.com/urfave/negroni.Wrap.func1(0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00, 0xc00000cd40)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:46 +0x4d\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0003b2700, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00, 0xc00000cd40)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x4e\ngithub.com/urfave/negroni.middleware.ServeHTTP(0x16797e0, 0xc0003b2700, 0xc0003b2760, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c\ngithub.com/pingcap/pd/pkg/apiutil/serverapi.(*redirector).ServeHTTP(0xc00000ec20, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00, 0xc00000cd20)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/pkg/apiutil/serverapi/middleware.go:107 +0xc0\ngithub.com/urfave/negroni.middleware.ServeHTTP(0x1676fc0, 0xc00000ec20, 0xc0003b2740, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c\ngithub.com/pingcap/pd/pkg/apiutil/serverapi.(*runtimeServiceValidator).ServeHTTP(0xc0002d6540, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00, 0xc00000cce0)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/pkg/apiutil/serverapi/middleware.go:64 +0xa2\ngithub.com/urfave/negroni.middleware.ServeHTTP(0x1676fe0, 0xc0002d6540, 0xc0003b2720, 0x7fa678fa6770, 0xc0000aca78, 0xc0006b6c00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003c67e0, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6c00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0xeb\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0002aa230, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6c00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/gorilla/mux@v1.6.1/mux.go:159 +0x104\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0002aa1c0, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6a00)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/gorilla/mux@v1.6.1/mux.go:159 +0x104\ngithub.com/urfave/negroni.Wrap.func1(0x7fa678fa6770, 0xc0000aca70, 0xc0006b6800, 0xc00000ccc0)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:46 +0x4d\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0003b2960, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6800, 0xc00000ccc0)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x4e\ngithub.com/urfave/negroni.middleware.ServeHTTP(0x16797e0, 0xc0003b2960, 0xc0003b29c0, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6800)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c\ngithub.com/urfave/negroni.(*Recovery).ServeHTTP(0xc0001a9540, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6800, 0xc00000cc80)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:193 +0xae\ngithub.com/urfave/negroni.middleware.ServeHTTP(0x16775c0, 0xc0001a9540, 0xc0003b29a0, 0x7fa678fa6770, 0xc0000aca70, 0xc0006b6800)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x9c\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0002d63c0, 0x16a1c00, 0xc0001867e0, 0xc0006b6800)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0xeb\nnet/http.(*ServeMux).ServeHTTP(0xc00158a640, 0x16a1c00, 0xc0001867e0, 0xc0006b6800)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\ngo.etcd.io/etcd/embed.(*accessController).ServeHTTP(0xc00151ab80, 0x16a1c00, 0xc0001867e0, 0xc0006b6800)\n\t/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190320044326-77d4b742cdbf/embed/serve.go:359 +0x1b5\nnet/http.serverHandler.ServeHTTP(0xc00158c1c0, 0x16a1c00, 0xc0001867e0, 0xc0006b6800)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc0002f5cc0, 0x16a6400, 0xc00158bf00)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2927 +0x38e\n", "content_type": "text/plain; charset=utf-8", "date": "Thu, 02 Jan 2020 06:26:07 GMT", "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "transfer_encoding": "chunked", "url": "http://172.19.136.22:12379/pd/api/v1/stores"}
...
```

**Comment by meilihao** [comment]
@liubo0127 today try again, got another error:
```
TASK [remove evict-leader-scheduler] ******************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: remove evict-leader-scheduler (3 retries left).
FAILED - RETRYING: remove evict-leader-scheduler (2 retries left).
FAILED - RETRYING: remove evict-leader-scheduler (1 retries left).
fatal: [172.19.136.22]: FAILED! => {"access_control_allow_headers": "accept, content-type, authorization", "access_control_allow_methods": "POST, GET, OPTIONS, PUT, DELETE", "access_control_allow_origin": "*", "attempts": 3, "changed": false, "connection": "close", "content": "null\n", "content_length": "5", "content_type": "application/json; charset=UTF-8", "cookies": {}, "date": "Tue, 07 Jan 2020 06:42:50 GMT", "json": null, "msg": "OK (5 bytes)", "redirected": false, "status": 200, "url": "http://172.19.136.22:12379/pd/api/v1/schedulers/evict-leader-scheduler-1"}
```

**Comment by liubo0127** [comment]
OK, we will check this error.
