### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0ylxDn/ansible/

### ISSUE THREAD

**Issue by jiangliuer326442** [pingcap/tidb-ansible#755]
按照文档操作 输入命令 **sudo pip install -r ./requirements.txt** 时候执行报错
详细报错信息如下：
````
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0ylxDn/ansible/setup.py", line 313, in <module>
        main()
      File "/tmp/pip-build-0ylxDn/ansible/setup.py", line 308, in main
        setup(**setup_params)
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'

You are using pip version 8.1.2, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
````
执行pip升级命令：   `pip install --upgrade pip`，升级pip之后再次执行，报错如下
````
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-JuyYZR/ansible/setup.py", line 313, in <module>
        main()
      File "/tmp/pip-install-JuyYZR/ansible/setup.py", line 308, in main
        setup(**setup_params)
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-JuyYZR/ansible/
````
tidb-ansible 版本为 v2.1.1

**Comment by superlzs0476** [comment]
Please install this version of pip.
shell`$ pip -V
pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)`

**Comment by superlzs0476** [comment]
This issue has been marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If you are still experiencing this issue, please test against a recent version of TiDB Ansible, and open a new issue with a full reproducer showing this issue.
